server:
  port: 9191

springbootwebflux:
  jjwt:
    password:
      encoder:
        secret: myjwtsecret
        iteration: 33
        keylength: 256
    secret: ThisIsSecretForJWTHS512SignatureAlgorithmThatMUSTHave512bitsKeySize
    expiration: 30000

spring:
  application:
    name: API-GATEWAY
  r2dbc:
    url: ${R2DBC_DATABASE_URL}
    username: ${R2DBC_DATABASE_USERNAME}
    password: ${R2DBC_DATABASE_PASSWORD}
    properties:
      sslMode: REQUIRE
    pool:
      enabled: true
      initialSize: 2
      maxSize: 2

  cloud:
    gateway:
      routes:
        - id: FOUNDATION-SERVICE
          uri: lb://FOUNDATION-SERVICE
          predicates:
            - Path=/category/**,/place/**
#          filters:
#            - name: CircuitBreaker
#              args:
#                name: FOUNDATION-SERVICE
#                allbackuri: forward:/placeServiceFallBack
        - id: RATING-SERVICE
          uri: lb://RATING-SERVICE
          predicates:
            - Path=/rating/**
#          filters:
#            - name: CircuitBreaker
#              args:
#                name: RATING-SERVICE
#                allbackuri: forward:/ratingServiceFallBack


#hystrix:
#  command:
#    fallbackcmd:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 4000
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include: hystrix.stream



eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: https://placeur-service-registry.herokuapp.com/eureka
  instance:
    hostname: 172.17.75.166


